title: Jerry Peng
description: portfolio
url: "https://peng-jerry.github.io/"
baseurl: ""

theme: minima

author:Jerry Peng
email: jp2011pa@gmail.com

minima:
  social_links:
    github: peng-jerry
    linkedin: yourlinkedin

header_pages:
  - about.md
  - projects.md
  - resume.md
