title: Jerry Peng
description: Portfolio
url: "https://peng-jerry.github.io/"
baseurl: ""

theme: minima

email: jp2011pa@gmail.com
github: peng-jerry
linkedin: yourlinkedin

social_links:
  github: peng-jerry
    

header_pages:
  - about.md
  - projects.md
  - resume.md
