title: Jerry Peng
description: Portfolio
url: "https://peng-jerry.github.io/"
baseurl: ""

theme: minima

email: jp2011pa@gmail.com
author: Jerry Peng

minima:
  social_links:
    github: peng-jerry
    linkedin: jerry-peng
    

header_pages:
  - about.md
  - projects.md
  - resume.md
